!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.26.2)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrap_solveke_solve (solvef2pywrap, m, ecc)
      use solveke, only : solve
      real(kind=8) m
      real(kind=8) ecc
      real(kind=8) solvef2pywrap
      solvef2pywrap = solve(m, ecc)
      end subroutine f2pywrap_solveke_solve
      
      subroutine f2pyinitsolveke(f2pysetupfunc)
      interface 
      subroutine f2pywrap_solveke_solve (solvef2pywrap, m, ecc)
      real(kind=8) m
      real(kind=8) ecc
      real(kind=8) solvef2pywrap
      end subroutine f2pywrap_solveke_solve
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(f2pywrap_solveke_solve)
      end subroutine f2pyinitsolveke


