!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.26.2)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrap_pq_pw_state (pw_statef2pywrap, tau)
      use pq, only : pw_state
      real(kind=8) tau
      real(kind=8) pw_statef2pywrap
      pw_statef2pywrap = pw_state(tau)
      end subroutine f2pywrap_pq_pw_state
      subroutine f2pywrap_pq_pw_stm (pw_stmf2pywrap, tau)
      use pq, only : pw_stm
      real(kind=8) tau
      real(kind=8) pw_stmf2pywrap(8,8)
      pw_stmf2pywrap = pw_stm(tau)
      end subroutine f2pywrap_pq_pw_stm
      subroutine f2pywrap_pq_pw_stt (pw_sttf2pywrap, tau)
      use pq, only : pw_stt
      real(kind=8) tau
      real(kind=8) pw_sttf2pywrap(8,8,8)
      pw_sttf2pywrap = pw_stt(tau)
      end subroutine f2pywrap_pq_pw_stt
      subroutine f2pywrap_pq_pw_stm_i (pw_stm_if2pywrap, tau)
      use pq, only : pw_stm_i
      real(kind=8) tau
      real(kind=8) pw_stm_if2pywrap(8,8)
      pw_stm_if2pywrap = pw_stm_i(tau)
      end subroutine f2pywrap_pq_pw_stm_i
      subroutine f2pywrap_pq_pw_stt_i (pw_stt_if2pywrap, tau)
      use pq, only : pw_stt_i
      real(kind=8) tau
      real(kind=8) pw_stt_if2pywrap(8,8,8)
      pw_stt_if2pywrap = pw_stt_i(tau)
      end subroutine f2pywrap_pq_pw_stt_i
      subroutine f2pywrap_pq_pw_prop_once (pw_prop_oncef2pywrap, ta, tb,&
     & xa, order)
      use pq, only : pw_prop_once
      real(kind=8) ta
      real(kind=8) tb
      integer order
      real(kind=8) xa(8)
      real(kind=8) pw_prop_oncef2pywrap(8)
      pw_prop_oncef2pywrap = pw_prop_once(ta, tb, xa, order)
      end subroutine f2pywrap_pq_pw_prop_once
      subroutine f2pywrap_pq_pw_prop_many (pw_prop_manyf2pywrap, ta, tb,&
     & xa, order, f2py_xa_d0, f2py_xa_d1)
      use pq, only : pw_prop_many
      real(kind=8) ta
      real(kind=8) tb
      integer order
      integer f2py_xa_d0
      integer f2py_xa_d1
      real(kind=8) xa(f2py_xa_d0,f2py_xa_d1)
      real(kind=8) pw_prop_manyf2pywrap(8,size(xa, 2))
      pw_prop_manyf2pywrap = pw_prop_many(ta, tb, xa, order)
      end subroutine f2pywrap_pq_pw_prop_many
      subroutine f2pywrap_pq_pw_prop_back (pw_prop_backf2pywrap, tb, ta,&
     & xb, order)
      use pq, only : pw_prop_back
      real(kind=8) tb
      real(kind=8) ta
      integer order
      real(kind=8) xb(8)
      real(kind=8) pw_prop_backf2pywrap(8)
      pw_prop_backf2pywrap = pw_prop_back(tb, ta, xb, order)
      end subroutine f2pywrap_pq_pw_prop_back
      subroutine f2pywrap_pq_pw_zmap (pw_zmapf2pywrap, tau, order)
      use pq, only : pw_zmap
      real(kind=8) tau
      integer order
      real(kind=8) pw_zmapf2pywrap
      pw_zmapf2pywrap = pw_zmap(tau, order)
      end subroutine f2pywrap_pq_pw_zmap
      
      subroutine f2pyinitpq(f2pysetupfunc)
      use pq, only : pw_init_v
      use pq, only : pw_init_n
      use pq, only : pw_stts_ab
      use pq, only : pw_stt_update
      use pq, only : pw_tensor_change_of_basis
      interface 
      subroutine f2pywrap_pq_pw_state (pw_statef2pywrap, tau)
      real(kind=8) tau
      real(kind=8) pw_statef2pywrap
      end subroutine f2pywrap_pq_pw_state 
      subroutine f2pywrap_pq_pw_stm (pw_stmf2pywrap, tau)
      real(kind=8) tau
      real(kind=8) pw_stmf2pywrap(8,8)
      end subroutine f2pywrap_pq_pw_stm 
      subroutine f2pywrap_pq_pw_stt (pw_sttf2pywrap, tau)
      real(kind=8) tau
      real(kind=8) pw_sttf2pywrap(8,8,8)
      end subroutine f2pywrap_pq_pw_stt 
      subroutine f2pywrap_pq_pw_stm_i (pw_stm_if2pywrap, tau)
      real(kind=8) tau
      real(kind=8) pw_stm_if2pywrap(8,8)
      end subroutine f2pywrap_pq_pw_stm_i 
      subroutine f2pywrap_pq_pw_stt_i (pw_stt_if2pywrap, tau)
      real(kind=8) tau
      real(kind=8) pw_stt_if2pywrap(8,8,8)
      end subroutine f2pywrap_pq_pw_stt_i 
      subroutine f2pywrap_pq_pw_prop_once (pw_prop_oncef2pywrap, ta, tb,&
     & xa, order)
      real(kind=8) ta
      real(kind=8) tb
      integer order
      real(kind=8) xa(8)
      real(kind=8) pw_prop_oncef2pywrap(8)
      end subroutine f2pywrap_pq_pw_prop_once 
      subroutine f2pywrap_pq_pw_prop_many (pw_prop_manyf2pywrap, ta, tb,&
     & xa, order, f2py_xa_d0, f2py_xa_d1)
      real(kind=8) ta
      real(kind=8) tb
      integer order
      integer f2py_xa_d0
      integer f2py_xa_d1
      real(kind=8) xa(f2py_xa_d0,f2py_xa_d1)
      real(kind=8) pw_prop_manyf2pywrap(8,size(xa, 2))
      end subroutine f2pywrap_pq_pw_prop_many 
      subroutine f2pywrap_pq_pw_prop_back (pw_prop_backf2pywrap, tb, ta,&
     & xb, order)
      real(kind=8) tb
      real(kind=8) ta
      integer order
      real(kind=8) xb(8)
      real(kind=8) pw_prop_backf2pywrap(8)
      end subroutine f2pywrap_pq_pw_prop_back 
      subroutine f2pywrap_pq_pw_zmap (pw_zmapf2pywrap, tau, order)
      real(kind=8) tau
      integer order
      real(kind=8) pw_zmapf2pywrap
      end subroutine f2pywrap_pq_pw_zmap
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(pw_init_v,pw_init_n,f2pywrap_pq_pw_state,f2pywr&
     &ap_pq_pw_stm,f2pywrap_pq_pw_stt,f2pywrap_pq_pw_stm_i,f2pywrap_pq_p&
     &w_stt_i,f2pywrap_pq_pw_prop_once,f2pywrap_pq_pw_prop_many,f2pywrap&
     &_pq_pw_prop_back,pw_stts_ab,pw_stt_update,pw_tensor_change_of_basi&
     &s,f2pywrap_pq_pw_zmap)
      end subroutine f2pyinitpq


